version: '3.7'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: rag_fastapi
    restart: always
    environment:
      - API_URL=http://fastapi:8000
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - rag-networks
    expose:
      - "8000"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: rag_streamlit
    restart: always
    environment:
      - API_URL=http://fastapi:8000
    volumes:
      - .:/app
    networks:
      - rag-networks
    expose:
      - "8501"

  nginx:
    depends_on:
      - fastapi
      - streamlit
    image: nginx:1.26.2-alpine-slim
    container_name: nginx
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "443:443"
    networks:
      - rag-networks

networks:
  rag-networks:
    driver: bridge
