FROM python:3.12

RUN apt-get update && apt-get install -y libgl1-mesa-glx && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/src

# ✅ Corrigir o PYTHONPATH
ENV PYTHONPATH=/app/src

CMD ["uvicorn", "backend.api:app", "--host", "0.0.0.0", "--port", "8000"]
