LIST_OFFENSIVE_WORDS = [
    "merda",
    "porra",
    "caralho",
    "bosta",
    "fdp",
    "cu",
    "foda-se",
    "desgraça",
    "imbecil",
    "otario",
    "burro",
    "idiota",
    "vagabundo",
    "filho da puta",
    "arrombado",
    "babaca",
    "canalha",
    "corno",
    "cuzao",
    "escroto",
    "pau no cu",
    "viado",
    "viadinho",
    "puta",
    "puto",
    "desgraçado",
    "moleque",
    "pilantra",
    "safado",
    "bobalhao",
    "cuzinho",
    "paspalho",
    "panaca",
    "trouxa",
    "chifrudo",
    "broxa",
    "imbecil",
    "lerdo",
    "lesado",
    "tonto",
    "tapado",
    "estupido",
    "mongol",
    "debil mental",
    "retardado",
    "nojento",
    "cretino",
    "verme",
    "pustema",
    "lazarento",
    "cabeça de bagre",
]
